alt+c run "sh" "-c" "printf '%s' \"$1\" | xclip -selection clipboard" -- "${path}"; show-text "Path copied"
ctrl+alt+e run "sh" "-c" "alacritty --command dam util edit \"$1\"" -- "${path}"; show-text "Editing in new window..."
alt+e run "sh" "-c" "alacritty --config-file ~/.config/alacritty/i3.toml --command dam util edit \"$1\"" -- "${path}"; show-text "Editing in new window..."
