- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ ansible_facts.user_dir }}/.local/share/systemd'
    - '{{ ansible_facts.user_dir }}/.local/share/systemd/user'
- name: Link systemd units
  ansible.builtin.file:
    src: '../../cronjobs/systemd/{{ item }}'
    dest: '{{ ansible_facts.user_dir }}/.local/share/systemd/user/{{ item }}'
    state: link
    owner: '{{ ansible_facts.user_id }}'
    group: '{{ ansible_facts.user_id }}'
  loop:
    - 'backup.service'
    - 'backup.timer'
- name: Start timer
  ansible.builtin.systemd_service:
    name: backup.timer
    scope: user
    state: started
    enabled: true
