#!/usr/bin/env python

import readline
import atexit
import os

python_history = os.path.expandvars('$HOME/.python_history')

try:
    readline.read_history_file(python_history)
except FileNotFoundError:
    pass


config_history = os.path.expandvars("$HOME/.config/python/python_history")

def move_history(new_hist):
    readline.write_history_file(new_hist)
    if os.path.exists(python_history):
        os.remove(python_history)

atexit.register(move_history, config_history)