#!/bin/bash

set -uo pipefail

log() {
	systemd-cat --identifier=hypr-script-wal "$@"
}

DIR="$HOME/Pictures/wallpapers"
WAL="$(
	find "$DIR" \
		-type f -printf '%f\n' \
		-not -name '*.txt' \
	| grep -v -f "$DIR/.gitignore" \
	| grep \
		--extended-regexp \
		--invert-match \
		'(ignore|\.gitignore|.+\.sh)' \
	| xargs -I{} echo "img:$DIR/{}:text:{}" \
	| wofi --show dmenu --prompt "Select a Wallpaper" --allow-images \
	| awk -F: '{ print $2 }'
)"
if [ $? -ne 0 ]; then
	echo "wallpaper request cancelled" | log --priority=info
	exit 0
fi

if [ ! -f "$WAL" ]; then
	echo "wallpaper \"$WAL\" does not exist" | log --priority=err
	exit 1
fi

set -e

# Set colors but not wallpaper
wal -n -i "$WAL"
# Reload waybar
killall -SIGUSR2 waybar
# Set wallpaper
hyprctl hyprpaper wallpaper ",$WAL,cover"

echo "set wallpaper to \"$WAL\"" | log -p=info
