#!/bin/bash

set -uo pipefail

log() {
	systemd-cat --identifier=hypr-script-wal "$@"
}

DIR="$HOME/Pictures/wallpapers"
WAL="$(
	find "$DIR" \
		-type f -printf '%f\n' \
		-not -name '*.txt' \
	| grep -v -f "$DIR/.gitignore" \
	| grep \
		--extended-regexp \
		--invert-match \
		'(ignore|\.gitignore)' \
	| xargs -I{} echo "img:$DIR/{}:text:{}" \
	| wofi --show dmenu --prompt "Select a Wallpaper" --allow-images \
	| awk -F: '{ print $2 }'
)"
if [ $? -ne 0 ]; then
	echo "wallpaper request cancelled" | log --priority=info
	exit 0
fi

if [ ! -f "$WAL" ]; then
	echo "wallpaper \"$WAL\" does not exist" | log --priority=err
	exit 1
fi

set -e
hyprctl hyprpaper preload "$WAL"
hyprctl hyprpaper wallpaper ",$WAL"

wal -i "$WAL"
# Reload waybar
killall -SIGUSR2 waybar
echo "set $WAL as wallpaper" | log --priority=info
