#!/usr/bin/bash

set -eu

wallust() {
	"$HOME/.config/cargo/bin/wallust" "$@"
}

THEMES=("$(wallust theme list | awk '/^-/ { print $2 }')")
THEMES+=("$(ls -1 "$HOME/.config/wallust/themes" | sed 's/.json$//g;')")
#echo "${THEMES[@]}"
# printf '%s\n' "${THEMES[@]}"
# exit 0
THEME="$(printf '%s\n' "${THEMES[@]}" | rofi -dmenu -p "Select a theme")"
if [ "${THEME}" == "list" ]; then
	i3-nagbar -t warning -m 'Cannot switch theme to "list"'
	exit 1
fi

# THEME="$(
# 	wallust theme list \
# 		| awk '/^-/ { print $2 }' \
# 		| rofi -dmenu -p "Select a theme"
# )"

OUT="$(wallust theme "$THEME")"
THEME_NAME="${THEME}"
if [ "$THEME" == "random" ]; then
	#echo "$OUT" | grep 'randomly selected' | awk '{print $5}' > "$HOME/.cache/wallust/theme"
	THEME_NAME="$(echo "$OUT" | grep 'randomly selected' | awk '{print $5}')"
# else
# 	echo "$THEME" >	"$HOME/.cache/wallust/theme"
fi

echo "${THEME_NAME}" >	"$HOME/.cache/wallust/theme"
echo "${THEME_NAME}" >>	"$HOME/.cache/wallust/themes.log"

polybar-msg cmd restart
i3-msg reload
