#!/usr/bin/bash

set -uo pipefail

wallust() {
	"$HOME/.config/cargo/bin/wallust" "$@"
}

log() {
	systemd-cat --identifier=i3-script-wal "$@"
}

capture() {
	if [ $1 -ne 0 ]; then
		shift
		systemd-cat --identifier=i3-script-wal "$@"
	fi
}

if [ -n "${1:-}" ]; then
	WAL="${1}"
else
	DIR="$HOME/Pictures/wallpapers"
	NAME="$(
		find "$DIR" \
			-type f -printf '%f\n' \
			-not -name '*.txt' \
		| xargs -I{} echo -e "{}\0icon\x1f$DIR/{}" \
		| rofi -dmenu -show-icons -p "Select a Wallpaper"
	)"
	if [ $? -ne 0 ]; then
		echo "wallpaper request cancelled" | log --priority=info
		exit 0
	fi
	WAL="$DIR/$NAME"
fi

set -e
if [ ! -f "$WAL" ]; then
	echo "wallpaper \"$WAL\" does not exist" | log --priority=err
	exit 1
fi

flags=()
case "${NAME:-}" in
	tatoo-girl-wouter-gort-3-bright-small.jpg|tatoo-girl-blue.jpg)
		flags+=("--bg-tile")
		;;
	*)
		flags+=("--bg-fill")
		;;
esac

#if [ -x "$HOME/.local/share/venv/bin/wal" ]; then
#	$HOME/.local/share/venv/bin/wal -n -i "$DIR/$WAL"
#elif command -v wallust >/dev/null; then
#	wallust pywal -i "$DIR/$WAL"
#fi

case "$(basename "$WAL")" in
	'splitface.png')
		THEME_NAME='Catppuccin-Frappé'
		wallust theme "$THEME_NAME"
		echo "${THEME_NAME}" >	"$HOME/.cache/wallust/theme"
		echo "${THEME_NAME}" >>	"$HOME/.cache/wallust/themes.log"
		;;
	*)
		rm -f "$HOME/.cache/wallust/theme"
		if ! wallust run "$WAL"; then
			notify-send -u normal -a 'i3/wallpaper' \
				"Failed to run wallust" \
				"Failed to set wallpaper with 'wallust run $WAL'"
			exit 1
		fi
		;;
esac

polybar-msg cmd restart
i3-msg reload
if ! feh "${flags[@]}" "$WAL"; then
	notify-send \
		-u normal \
		-a 'i3/wallpaper' \
		-t 10000 \
		"Failed to set wallpaper" \
		"Failed to set wallpaper with 'feh ${flags[*]} $WAL'"
fi

notify-send \
	-u normal \
	-a 'i3/wallpaper' \
	-t 3000 \
	"Wallpaper Set" \
	"Set wallpaper to $WAL"
