[general]

# Pulled from https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/base.toml",
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/themes/terafox.toml",
]
