# https://alacritty.org/config-alacritty.html
[general]

[font]
size = 11.25
# size = 10
#normal = { family = "FiraMono Nerd Font Mono", style = "Medium" }
#noraml = { family = "Iosevka Nerd Font Mono", style = "Bold" }
normal = { family = "RobotoMono Nerd Font Mono" }

[mouse]
hide_when_typing = true

[scrolling]
history = 1000

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"
title = "lol"

[window.padding]
x = 0
y = 0

[colors]
transparent_background_colors = true

[colors.cursor]
text = "#000000"
# text = "#ffffff"
