[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control|Shift"
#
# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mods = "Control|Shift"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"

[[keyboard.bindings]]
key = "Enter"
mods = "Alt"
chars = "\u001b[13;3u"
